#!/bin/bash
CMD=$1
IP=$2
DIR=$3
if [[ CMD == "clean" ]]; then
    gradle clean
fi
if [[ $? == 0 ]]; then
    gulp

    if [[ $DIR == "" ]]; then
        DIR="www"
    fi
    echo "$USER@$IP"
    if [[ ! -d deploy ]]; then
        mkdir deploy
    fi
    cp app/build/libs/*.jar deploy/
    cp config.properties deploy/
    cp run deploy/
    cp kiosk deploy/
    cp run.bat deploy/

    #rsync -ia resources/public app/src/main/resources/
    #rsync -ia resources/public deploy/resources/
    #rsync -ia --exclude=app/lib/ deploy/lib/

    export GRADLE_COMPILE_ONLY=true
    gradle shadowJar
    if [[ $IP == "" ]]; then
        IP="192.168.20.82"
        DIR="www"
        rsync -av --exclude='deploy/log/*' deploy/resources deploy/*.jar deploy/config.properties deploy/kiosk deploy/run "sem@$IP:$DIR/."
    else
        DIR="www"
       rsync -av --exclude='deploy/log/*' deploy/resources deploy/*.jar deploy/config.properties deploy/kiosk deploy/run "sem@$IP:$DIR/."
    fi
    LOG=log/
    if [[ -f "$LOG" ]]; then
        echo $LOG
    fi

    if [[ $? != 0 ]]; then
        echo "************************ COMPILE FAILED ****************************"
    fi
else
    echo "************************ COMPILE FAILED ****************************"
    exit
fi
