#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu"* ]]; then # linux
  echo "OS is Ubuntu"
  while true ; do
    sleep 20
    #xdotool key ctrl+r
    chromium --kiosk http://localhost:5555/
    break
  done
elif [[ "$OSTYPE" == "linux-gnueabihf" ]]; then
  while true ; do
    sleep 20
    #xdotool key ctrl+r
    chromium --kiosk http://localhost:5555/
    break
  done
elif [[ "$OSTYPE" == "darwin"* ]]; then # Mac OS
  echo "OS is Mac"
  /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --kiosk --app=http://localhost:5555/
else
  echo "Unknown OS"
fi